export const USER_SETTING_LOGOUT = 'USER_SETTING_LOGOUT';
export const USER_SETTING_LOGOUT_SUCCESS = 'USER_SETTING_LOGOUT_SUCCESS';
export const USER_SETTING_LOGOUT_FAILURE = 'USER_SETTING_LOGOUT_FAILURE';