module.exports = {
    SPLASH_SCREEN_TEXT: 'Incident Management App',
    LOGIN: 'Login',
    WELCOME: 'Welcome to',
    App_NAME: 'Incident Management App',
    EMAIL: 'Email',
    PASSWORD: 'Password',
    FORGOT_PASSWORD: 'Forgot Password',
    COMPANY_NAME: 'Acid Survivors Foundation',
    EMAIL_EMPTY_MESSAGE: 'Email can not be empty',
    PASSWORD_EMPTY_MESSAGE: 'Password can not be empty',
    DASHBOARD_TITLE: 'Dashboard',
    LATEST_CASE: 'Latest Case',
    VICTIM_NAME_LABEL: 'Victim Name',
    AGE_LABEL: 'Age',
    PARENTS_LABEL: 'Parents',
    GENDER_LABEL: 'Gender',
    PREVIOUS_CASE: 'Previous Cases',
    YOU_DO_NOT_HAVE_ANY_CASE: 'You haven\'t created any case',
    PLEASE_POST_YOUR_CASE_HERE: ' Please post your case here',
    ADD_CASE: 'Add Case',
    ALL_CASE: 'All Cases',
    WRITE_A_COMMENT: 'Write a comment',
    COMMENT: 'Comment',
    COMMENT_EMPTY_MESSAGE: 'Comment can not be empty',
    VICTIM_INFO: 'Victim Info',
    PARENTS_OR_HUSBAND: 'Parents/Husband',
    LOCATION: 'Location',
    NEXT: 'Next',
    VICTIM_NAME_EMPTY_MESSAGE: 'Victim name can not be empty',
    PARENTS_EMPTY_MESSAGE: 'Parents/Husband name can not be empty',
    AGE_EMPTY_MESSAGE: 'Age can not be empty',
    LOCATION_EMPTY_MESSAGE: 'Location can not be empty',
    SELECT_YOUR_GENDER: 'Please select your gender',
    CASE_INFO: 'Case Info',
    CASE_NAME: 'Case Name',
    CASE_DETAILS: 'Case Details',
    CASE_NAME_EMPTY_MESSAGE: 'Case name can not be empty',
    CASE_DETAILS_EMPTY_MESSAGE: 'Case details can not be empty',
    SELECT_VIOLENCE_TYPE: 'Please select violence type',
    ATTACHMENT_INFO: 'Attachment Info',
    UPLOAD_PHOTO: 'Upload Photo',
    UPLOAD_FILE: 'Upload File',
    VALID_EXTENSION_MESSAGE: 'File is not supported',
    ATTACHMENT: 'Attachment',
    PHOTO: 'Photo',
    SELECT_PICTURE_TEXT: 'Select Picture',
    ATTACHMENT_NOT_REQUIRED: 'Note: If you don\'t have any attachment please proceed with next',
    DELETE_PHOTO_WARNING: 'Are you sure you want to delete your photo?',
    DELETE_FILE_WARNING: 'Are you sure you want to delete your File?',
    DELETE_PHOTO: 'Delete Photo',
    DELETE_FILE: 'Delete File',
    OK_BUTTON: 'Ok',
    CANCEL_BUTTON: 'Cancel',
    REFEREED: 'Refereed',
    REFEREED_TO: 'Refereed To: ',
    SUBMIT_FOR_REVIEW: 'Submit for review',
    SETTINGS: 'Setting',
    EDIT_PROFILE_LABEL: 'Edit Profile',
    LOG_OUT_LABEL: 'Log Out',
    ACCOUNT_SETTING_LABEL: 'Account & Settings',
    LOG_OUT_WARNING: 'Are you logout now?',
    UPDATE_PROFILE: 'Update Profile',
    NAME: 'Name',
    DESIGNATION: 'Designation',
    PHONE_NUMBER: 'Phone Number',
    UPDATE: 'Update',
    USER_NAME_EMPTY_MESSAGE: 'Name can not be empty',
    PHONE_NUMBER_EMPTY_MESSAGE: 'Phone number can not be empty',
    DESIGNATION_EMPTY_MESSAGE: 'Designation can not be empty',
    PHONE_NUMBER_FORMAT_NOT_CORRECT: 'Phone number format is not correct',
    CHANGE_PASSWORD: 'Change Password',
    OLD_PASSWORD: 'Old Password',
    NEW_PASSWORD: 'New Password',
    CONFIRM_PASSWORD: 'Confirm Password',
    OLD_PASSWORD_EMPTY_MESSAGE: 'Old password can not be empty',
    NEW_PASSWORD_EMPTY_MESSAGE: 'New password can not be empty',
    CONFIRM_PASSWORD_EMPTY_MESSAGE: 'Confirm password can not be empty',
    PASSWORD_NOT_MATCHED_ERROR_MESSAGE: 'Password does not match',
    ALREADY_ACCOUNT: 'Already have an account?',
    OTP: 'Otp',
    FIELD_CAN_NOT_EMPTY_TEXT: 'Field can not be empty',
    RESEND_OTP_TEXT: 'Resend OTP?',
    LOGIN_ERROR_MESSAGE: 'Phone number or Password is not correct',
    INCIDENT_CREATE_SUCCESSFULLY: 'Incident Create Successfully',
    SOMETHING_WAS_WRONG: 'Something was wrong',
    PASSWORD_CHANGED_SUCCESSFULLY: 'Password change successfully, Please login again',
    UPDATE_PROFILE_SUCCESSFULLY: 'Update profile successfully',
    OTP_SEND_SUCCESSFULLY: 'OTP send to your mobile successfully',
    OTP_RESEND_SUCCESSFULLY: 'OTP resend to your mobile successfully',
    PASSWORD_RESET_SUCCESSFULLY: 'Password reset successfully',
    LOGOUT_SUCCESSFULLY: 'Logout successfully'
};