module.exports = {
    FONT_SIZE_XXL: 30,
    FONT_SIZE_XL: 25,
    FONT_SIZE_L: 22,
    FONT_SIZE_M: 18,
    FONT_SIZE_S: 14,
    FONT_SIZE_EXTRA_S: 12,
    FONT_SIZE_EXTRA_SS: 11,
    BUTTON_TEXT_SIZE: 16,
    BUTTON_HEIGHT: 40,
    TOOLBAR_ICON_SIZE: 24,
    FLOATING_BUTTON_SIZE: 50,
    FLOATING_BUTTON_ICON_SIZE: 24
};