module.exports = {
    NAME: 'NAME',
    PHONE_NUMBER: 'PHONE_NUMBER',
    DESIGNATION: 'DESIGNATION',
    OLD_PASSWORD: 'OLD_PASSWORD',
    NEW_PASSWORD: 'NEW_PASSWORD',
    CONFIRM_PASSWORD: 'CONFIRM_PASSWORD'
};