export const COMMENT_SCREEN_ALL_COMMENT = 'COMMENT_SCREEN_ALL_COMMENT';
export const COMMENT_SCREEN_ALL_COMMENT_SUCCESS = 'COMMENT_SCREEN_ALL_COMMENT_SUCCESS';
export const COMMENT_SCREEN_ALL_COMMENT_FAILURE = 'COMMENT_SCREEN_ALL_COMMENT_FAILURE';

export const COMMENT_SCREEN_INITIALIZE_VALUE = 'COMMENT_SCREEN_INITIALIZE_VALUE';

export const COMMENT_SCREEN_ADD_NEW_COMMENT = 'COMMENT_SCREEN_ADD_NEW_COMMENT';
export const COMMENT_SCREEN_ADD_NEW_COMMENT_SUCCESS = 'COMMENT_SCREEN_ADD_NEW_COMMENT_SUCCESS';
export const COMMENT_SCREEN_ADD_NEW_COMMENT_FAILURE = 'COMMENT_SCREEN_ADD_NEW_COMMENT_FAILURE';