export const INCIDENT_CREATE_SELECT_GENDER = 'INCIDENT_CREATE_SELECT_GENDER';
export const INCIDENT_CREATE_SELECT_VIOLENCE_TYPE = 'INCIDENT_CREATE_SELECT_VIOLENCE_TYPE';
export const INCIDENT_CREATE_ADD_FILE = 'INCIDENT_CREATE_ADD_FILE';
export const INCIDENT_CREATE_ADD_PHOTO = 'INCIDENT_CREATE_ADD_PHOTO';
export const INCIDENT_CREATE_DELETE_PHOTO = 'INCIDENT_CREATE_DELETE_PHOTO';
export const INCIDENT_CREATE_DELETE_FILE = 'INCIDENT_CREATE_DELETE_FILE';
export const INCIDENT_CREATE_UPDATE_REFEREED_CHECKBOX = 'INCIDENT_CREATE_UPDATE_REFEREED_CHECKBOX';
export const INCIDENT_CREATE_INITIAL_CREATE_INFO = 'INCIDENT_CREATE_INITIAL_CREATE_INFO';
export const INCIDENT_CREATE_INITIAL_ATTACHMENT_PAGE_INFO = 'INCIDENT_CREATE_INITIAL_ATTACHMENT_PAGE_INFO';

export const INCIDENT_CREATE_GET_SETTING = 'INCIDENT_CREATE_GET_SETTING';
export const INCIDENT_CREATE_GET_SETTING_SUCCESS = 'INCIDENT_CREATE_GET_SETTING_SUCCESS';
export const INCIDENT_CREATE_GET_SETTING_FAILURE = 'INCIDENT_CREATE_GET_SETTING_FAILURE';

export const INCIDENT_CREATE_SET_INCIDENT_INFO = 'INCIDENT_CREATE_SET_INCIDENT_INFO';

export const INCIDENT_CREATE_NEW_INCIDENT = 'INCIDENT_CREATE_NEW_INCIDENT';
export const INCIDENT_CREATE_NEW_INCIDENT_SUCCESS = 'INCIDENT_CREATE_NEW_INCIDENT_SUCCESS';
export const INCIDENT_CREATE_NEW_INCIDENT_FAILURE = 'INCIDENT_CREATE_NEW_INCIDENT_FAILURE';

export const TICKET_ETA_ERT_SET = 'TICKET_ETA_ERT_SET';
export const TICKET_ETA_ERT_SET_API = 'TICKET_ETA_ERT_SET_API';
export const TICKET_ETA_ERT_SET_API_SUCCESS = 'TICKET_ETA_ERT_SET_API_SUCCESS';
export const TICKET_ETA_ERT_SET_API_FAILURE = 'TICKET_ETA_ERT_SET_API_FAILURE';

export const TICKET_UPDATE_SUCCESS = 'TICKET_UPDATE_SUCCESS';
export const TICKET_UPDATE_FAILURE = 'TICKET_UPDATE_FAILURE';


export const TICKET_STATUS = 'TICKET_STATUS';
export const TICKET_STATUS_API = 'TICKET_STATUS_API';
export const TICKET_STATUS_API_SUCCESS = 'TICKET_STATUS_API_SUCCESS';
export const TICKET_STATUS_API_FAILURE = 'TICKET_STATUS_API_FAILURE';
